### ISSUE TITLE
'Calendar' object has no attribute 'as_string'

### ISSUE THREAD

**Issue by douglaskastle** [collective/icalendar#32]
After I manually install pytz (see issue #31)I got another warning, 'Calendar' object has no attribute 'as_string', here is the most simplest code I could do to trip the error (note I didn't add an event here but it is still an error)

``` python
from icalendar import Calendar, Event

cal = Calendar()
cal.add('prodid', '-//example//sdf.1//')
cal.add('version', '3.0')

f = open('example.ics', 'wb')
f.write(cal.as_string())
f.close()
```

This code also works correctly in icalendar 2.2, fails in icalendar 3.0.1b1
