### ISSUE TITLE
python 2.5 incompatbility

### ISSUE THREAD

**Issue by RossBoylan** [collective/icalendar#68]
Symptom:  python karm-repair.py
Traceback (most recent call last):
  File "karm-repair.py", line 6, in <module>
    cal = Calendar.from_ical(open('test1.ics', 'rb').read())
  File "/usr/local/lib/python2.5/site-packages/icalendar-3.2dev-py2.5.egg/icalendar/cal.py", line 457, in from_ical
    raise ValueError('Found no components where '
AttributeError: 'str' object has no attribute 'format'

Line 457 has
        if len(comps) < 1:
            raise ValueError('Found no components where '
                             'exactly one is required: {st!r}'.format(**locals()))

I think the problem is that the format feature was introduced more recently than Python 2.5.
The descriptions of the package says it works with Python 2.4-2.7.

The error probably arose because my test file has something wrong with it.  This issue is not about that problem, but about the fact that the error handler doesn't work properly.

Using collective-icalendar-3.1-4-gf64efaf.zip downloaded earlier today on a Debian Lenny system (which is old).
